openapi: 3.0.3
info:
  title: MIA Cache Api
  description: MIA -> reset environment/poolCache, mark/unmark process for edit
  version: '2.0'
  contact:
    name: OurCompany
    url: https://www.ourcompany.com/company/about-ourcompany/contact-us.html
servers:
  - url: https://atp-public-gateway:8080/api/atp-mia/v1
  - url: http://localhost:8080
tags:
  - name: mia-cache-controller
    description: MIA Cache Controller
paths:
  /rest/resetEnvCaches:
    post:
      tags:
        - mia-cache-controller
      summary: Reset mia environment Caches
      operationId: resetEnvironmentCaches
      parameters:
        - name: projectId
          in: query
          description: projectId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: boolean
        201:
          description: Created
          content: { }
        401:
          description: Unauthorized
          content: { }
        403:
          description: Forbidden
          content: { }
        404:
          description: Not Found
          content: { }
      deprecated: false
  /rest/resetPoolCache:
    post:
      tags:
        - mia-cache-controller
      summary: Reset mia poolcache
      operationId: resetPoolCache
      parameters:
        - name: projectId
          in: query
          description: projectId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: boolean
        201:
          description: Created
          content: { }
        401:
          description: Unauthorized
          content: { }
        403:
          description: Forbidden
          content: { }
        404:
          description: Not Found
          content: { }
      deprecated: false
  /rest/flow/resetCache:
    post:
      tags:
        - mia-cache-controller
      summary: Reset DB Cache for Project
      operationId: resetDbCache
      parameters:
        - name: projectId
          in: query
          description: projectId
          required: true
          schema:
            type: string
            format: uuid
        - name: env
          in: query
          description: environmentName
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: boolean
        201:
          description: Created
          content: { }
        401:
          description: Unauthorized
          content: { }
        403:
          description: Forbidden
          content: { }
        404:
          description: Not Found
          content: { }
      deprecated: false
  /rest/resetConfigurationCache:
    post:
      tags:
        - mia-cache-controller
      summary: Reset mia configuration cache
      operationId: resetConfigurationCache
      parameters:
        - name: projectId
          in: query
          description: projectId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: boolean
        201:
          description: Created
          content: { }
        401:
          description: Unauthorized
          content: { }
        403:
          description: Forbidden
          content: { }
        404:
          description: Not Found
          content: { }
      deprecated: false
