openapi: 3.0.1
info:
  title: MIA History Change API
  description: MIA History Change API
  version: '1.0'
  contact:
    name: OurCompany
    url: https://www.ourcompany.com/company/about-ourcompany/contact-us.html
servers:
  - url: https://atp-public-gateway:8080/api/atp-mia/v1
  - url: http://localhost:8080
tags:
  - name: mia-history-changes-controller
    description: MIA History Change controller
paths:
  /rest/history/{projectId}/{itemType}/{id}:
    get:
      tags:
        - mia-history-changes-controller
      summary: finds all changes history for defined object
      operationId: getAllHistory
      parameters:
        - name: projectId
          in: path
          schema:
            type: string
            format: uuid
            description: project id for current entity
          required: true
        - name: itemType
          in: path
          schema:
            type: string
            description:
          required: true
        - name: id
          in: path
          schema:
            type: string
            format: uuid
          required: true
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: 'openapi-mia-models-v2.yaml#/components/schemas/HistoryItemResponse'
        '400':
          description: History for Entity type = '" + itemType + "' is not supported
        '404':
          description: Entity Id not found

  /rest/history/restore/{projectId}/{itemType}/{id}/revision/{revisionId}:
    post:
      tags:
        - mia-history-changes-controller
      summary: Restore the state of the provided entity to defined revision
      operationId: restoreToRevision
      parameters:
        - name: projectId
          in: path
          schema:
            type: string
            format: uuid
            description: project id for current entity
          required: true
        - name: itemType
          in: path
          schema:
            type: string
            description:
          required: true
        - name: id
          in: path
          schema:
            type: string
            format: uuid
            description: uuid of restored entity
          required: true
          example: '83b22327-2f68-4f8b-96ab-1d3670248b9f'
        - name: revisionId
          in: path
          schema:
            type: integer
            description: target revision number for restored entity
          required: true
          example: 3
      responses:
        '200':
          description: 'OK'
        '403':
          description: 'Forbidden'
        '404':
          description: 'Entity Id not found'
        '500':
          description: 'Revision was not restored'

  /rest/entityversioning/{projectId}/{itemType}/{uuid}:
    get:
      tags:
        - mia-history-changes-controller
      summary: getEntitiesByVersion
      operationId: getEntitiesByVersion
      parameters:
        - name: projectId
          in: path
          description: projectId
          required: true
          style: simple
          schema:
            type: string
            format: uuid
        - name: itemType
          in: path
          description: itemType
          required: true
          style: simple
          schema:
            type: string
        - name: uuid
          in: path
          description: uuid
          required: true
          style: simple
          schema:
            type: string
            format: uuid
        - name: versions
          in: query
          description: versions
          required: true
          style: form
          explode: true
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: 'openapi-mia-models-v2.yaml#/components/schemas/CompareEntityResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
