apiVersion: v1
kind: Secret
metadata:
  name: kube2vcs
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": "before-hook-creation"
stringData:
  pass: "{{ .Values.infraPassword | default "" }}"
  user: "{{ .Values.infraUser | default "x_kube2vcs" }}"
type: Opaque