openapi: 3.0.1
info:
  title: Api Documentation
  description: Api Documentation
  version: '1.0'
  contact:
    name: OurCompany
    url: https://www.ourcompany.com/company/about-ourcompany/contact-us.html
servers:
  - url: //localhost:8080/
tags:
  - name: candidates-controller
    description: candidates Controller
paths:
  /api/mia/project/{projectId}/candidates:
    get:
      tags:
        - candidates
      summary: getCandidates
      operationId: getCandidates
      parameters:
        - name: projectId
          in: path
          description: projectId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExportCandidate'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
      deprecated: false

components:
  schemas:
    ExportCandidate:
      title: ExportCandidate
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        entities:
          type: array
          items:
            $ref: '#/components/schemas/ExportEntitiesCandidate'
    ExportEntitiesCandidate:
      title: ExportEntitiesCandidate
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        entityType:
          type: string
        entities:
          type: array
          items:
            $ref: '#/components/schemas/ExportEntitiesCandidate'
